# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1098, 427)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.voletNavigation = QtWidgets.QWidget(self.centralwidget)
        self.voletNavigation.setObjectName("voletNavigation")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.voletNavigation)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.boutonDepenses = QtWidgets.QPushButton(self.voletNavigation)
        self.boutonDepenses.setCheckable(True)
        self.boutonDepenses.setAutoExclusive(True)
        self.boutonDepenses.setObjectName("boutonDepenses")
        self.verticalLayout_2.addWidget(self.boutonDepenses)
        self.boutonCategories = QtWidgets.QPushButton(self.voletNavigation)
        self.boutonCategories.setCheckable(True)
        self.boutonCategories.setAutoExclusive(True)
        self.boutonCategories.setObjectName("boutonCategories")
        self.verticalLayout_2.addWidget(self.boutonCategories)
        self.boutonEntites = QtWidgets.QPushButton(self.voletNavigation)
        self.boutonEntites.setCheckable(True)
        self.boutonEntites.setAutoExclusive(True)
        self.boutonEntites.setObjectName("boutonEntites")
        self.verticalLayout_2.addWidget(self.boutonEntites)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.boutonParametres = QtWidgets.QPushButton(self.voletNavigation)
        self.boutonParametres.setObjectName("boutonParametres")
        self.verticalLayout_2.addWidget(self.boutonParametres)
        self.boutonAPropos = QtWidgets.QPushButton(self.voletNavigation)
        self.boutonAPropos.setObjectName("boutonAPropos")
        self.verticalLayout_2.addWidget(self.boutonAPropos)
        self.horizontalLayout.addWidget(self.voletNavigation)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.ongletAPropos = QtWidgets.QWidget()
        self.ongletAPropos.setObjectName("ongletAPropos")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.ongletAPropos)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_17 = QtWidgets.QLabel(self.ongletAPropos)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_7.addWidget(self.label_17)
        self.label_16 = QtWidgets.QLabel(self.ongletAPropos)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_7.addWidget(self.label_16)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_18 = QtWidgets.QLabel(self.ongletAPropos)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.ongletAPropos)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_19)
        self.label_20 = QtWidgets.QLabel(self.ongletAPropos)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.ongletAPropos)
        self.label_21.setObjectName("label_21")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_21)
        self.label_22 = QtWidgets.QLabel(self.ongletAPropos)
        self.label_22.setObjectName("label_22")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.label_23 = QtWidgets.QLabel(self.ongletAPropos)
        self.label_23.setObjectName("label_23")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_23)
        self.verticalLayout_7.addLayout(self.formLayout_4)
        self.tabWidget.addTab(self.ongletAPropos, "")
        self.ongletParametres = QtWidgets.QWidget()
        self.ongletParametres.setObjectName("ongletParametres")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.ongletParametres)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.tabWidget.addTab(self.ongletParametres, "")
        self.ongletDepenses = QtWidgets.QWidget()
        self.ongletDepenses.setObjectName("ongletDepenses")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ongletDepenses)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_36 = QtWidgets.QLabel(self.ongletDepenses)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_4.addWidget(self.label_36)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.boutonAjouter = QtWidgets.QPushButton(self.ongletDepenses)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/list-add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boutonAjouter.setIcon(icon)
        self.boutonAjouter.setObjectName("boutonAjouter")
        self.horizontalLayout_2.addWidget(self.boutonAjouter)
        self.pushButton = QtWidgets.QPushButton(self.ongletDepenses)
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/document-edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.boutonRetirer = QtWidgets.QPushButton(self.ongletDepenses)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/list-remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boutonRetirer.setIcon(icon2)
        self.boutonRetirer.setObjectName("boutonRetirer")
        self.horizontalLayout_2.addWidget(self.boutonRetirer)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.widget = QtWidgets.QWidget(self.ongletDepenses)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableau = QtWidgets.QTableView(self.widget)
        self.tableau.setObjectName("tableau")
        self.verticalLayout_3.addWidget(self.tableau)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.listWidget = QtWidgets.QListWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_3.addWidget(self.listWidget)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.widget)
        self.tabWidget.addTab(self.ongletDepenses, "")
        self.creerDepense = QtWidgets.QWidget()
        self.creerDepense.setObjectName("creerDepense")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.creerDepense)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_26 = QtWidgets.QLabel(self.creerDepense)
        self.label_26.setObjectName("label_26")
        self.verticalLayout.addWidget(self.label_26)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.creerDepense)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.creerDepense)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.creerDepense)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.creerDepense)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_3 = QtWidgets.QLabel(self.creerDepense)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.textEdit = QtWidgets.QTextEdit(self.creerDepense)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textEdit)
        self.label_4 = QtWidgets.QLabel(self.creerDepense)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.creerDepense)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        self.doubleSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox.setReadOnly(True)
        self.doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.label_14 = QtWidgets.QLabel(self.creerDepense)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.tableView_2 = QtWidgets.QTableView(self.creerDepense)
        self.tableView_2.setObjectName("tableView_2")
        self.verticalLayout.addWidget(self.tableView_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.creerDepense)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.tabWidget.addTab(self.creerDepense, "")
        self.voirDepense = QtWidgets.QWidget()
        self.voirDepense.setObjectName("voirDepense")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.voirDepense)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_25 = QtWidgets.QLabel(self.voirDepense)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_5.addWidget(self.label_25)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.voirDepense)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.voirDepense)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_6 = QtWidgets.QLabel(self.voirDepense)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.voirDepense)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_7 = QtWidgets.QLabel(self.voirDepense)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.textEdit_2 = QtWidgets.QTextEdit(self.voirDepense)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textEdit_2)
        self.label_8 = QtWidgets.QLabel(self.voirDepense)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.voirDepense)
        self.doubleSpinBox_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_2.setReadOnly(True)
        self.doubleSpinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_2)
        self.verticalLayout_5.addLayout(self.formLayout_2)
        self.label_9 = QtWidgets.QLabel(self.voirDepense)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.tableView = QtWidgets.QTableView(self.voirDepense)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_5.addWidget(self.tableView)
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(self.voirDepense)
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.verticalLayout_5.addWidget(self.buttonBox_2)
        self.tabWidget.addTab(self.voirDepense, "")
        self.editerDepense = QtWidgets.QWidget()
        self.editerDepense.setObjectName("editerDepense")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.editerDepense)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_24 = QtWidgets.QLabel(self.editerDepense)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_6.addWidget(self.label_24)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtWidgets.QLabel(self.editerDepense)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.editerDepense)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.editerDepense)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.editerDepense)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.textEdit_3 = QtWidgets.QTextEdit(self.editerDepense)
        self.textEdit_3.setObjectName("textEdit_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textEdit_3)
        self.label_13 = QtWidgets.QLabel(self.editerDepense)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.editerDepense)
        self.doubleSpinBox_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_3.setReadOnly(True)
        self.doubleSpinBox_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_3)
        self.comboBox_2 = QtWidgets.QComboBox(self.editerDepense)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.verticalLayout_6.addLayout(self.formLayout_3)
        self.label_15 = QtWidgets.QLabel(self.editerDepense)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.tableView_3 = QtWidgets.QTableView(self.editerDepense)
        self.tableView_3.setObjectName("tableView_3")
        self.verticalLayout_6.addWidget(self.tableView_3)
        self.buttonBox_3 = QtWidgets.QDialogButtonBox(self.editerDepense)
        self.buttonBox_3.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_3.setObjectName("buttonBox_3")
        self.verticalLayout_6.addWidget(self.buttonBox_3)
        self.tabWidget.addTab(self.editerDepense, "")
        self.ongletMembres = QtWidgets.QWidget()
        self.ongletMembres.setObjectName("ongletMembres")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.ongletMembres)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_37 = QtWidgets.QLabel(self.ongletMembres)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_14.addWidget(self.label_37)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.ongletMembres)
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.ongletMembres)
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.ongletMembres)
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_14.addLayout(self.horizontalLayout_4)
        self.listView = QtWidgets.QListView(self.ongletMembres)
        self.listView.setObjectName("listView")
        self.verticalLayout_14.addWidget(self.listView)
        self.tabWidget.addTab(self.ongletMembres, "")
        self.creerMembre = QtWidgets.QWidget()
        self.creerMembre.setObjectName("creerMembre")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.creerMembre)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_38 = QtWidgets.QLabel(self.creerMembre)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_8.addWidget(self.label_38)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_27 = QtWidgets.QLabel(self.creerMembre)
        self.label_27.setObjectName("label_27")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.creerMembre)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.verticalLayout_8.addLayout(self.formLayout_5)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem5)
        self.buttonBox_4 = QtWidgets.QDialogButtonBox(self.creerMembre)
        self.buttonBox_4.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_4.setObjectName("buttonBox_4")
        self.verticalLayout_8.addWidget(self.buttonBox_4)
        self.tabWidget.addTab(self.creerMembre, "")
        self.voirMembre = QtWidgets.QWidget()
        self.voirMembre.setObjectName("voirMembre")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.voirMembre)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_45 = QtWidgets.QLabel(self.voirMembre)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_17.addWidget(self.label_45)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem6)
        self.formLayout_11 = QtWidgets.QFormLayout()
        self.formLayout_11.setObjectName("formLayout_11")
        self.label_46 = QtWidgets.QLabel(self.voirMembre)
        self.label_46.setObjectName("label_46")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.voirMembre)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_11)
        self.verticalLayout_17.addLayout(self.formLayout_11)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem7)
        self.buttonBox_10 = QtWidgets.QDialogButtonBox(self.voirMembre)
        self.buttonBox_10.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox_10.setObjectName("buttonBox_10")
        self.verticalLayout_17.addWidget(self.buttonBox_10)
        self.tabWidget.addTab(self.voirMembre, "")
        self.editerMembre = QtWidgets.QWidget()
        self.editerMembre.setObjectName("editerMembre")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.editerMembre)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_40 = QtWidgets.QLabel(self.editerMembre)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_10.addWidget(self.label_40)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem8)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_29 = QtWidgets.QLabel(self.editerMembre)
        self.label_29.setObjectName("label_29")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.editerMembre)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.verticalLayout_10.addLayout(self.formLayout_7)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem9)
        self.buttonBox_6 = QtWidgets.QDialogButtonBox(self.editerMembre)
        self.buttonBox_6.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_6.setObjectName("buttonBox_6")
        self.verticalLayout_10.addWidget(self.buttonBox_6)
        self.tabWidget.addTab(self.editerMembre, "")
        self.ongletCategories = QtWidgets.QWidget()
        self.ongletCategories.setObjectName("ongletCategories")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.ongletCategories)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_41 = QtWidgets.QLabel(self.ongletCategories)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_15.addWidget(self.label_41)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.ongletCategories)
        self.pushButton_6.setText("")
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.ongletCategories)
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.pushButton_7 = QtWidgets.QPushButton(self.ongletCategories)
        self.pushButton_7.setText("")
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.verticalLayout_15.addLayout(self.horizontalLayout_5)
        self.tableView_4 = QtWidgets.QTableView(self.ongletCategories)
        self.tableView_4.setObjectName("tableView_4")
        self.verticalLayout_15.addWidget(self.tableView_4)
        self.tabWidget.addTab(self.ongletCategories, "")
        self.creerCategorie = QtWidgets.QWidget()
        self.creerCategorie.setObjectName("creerCategorie")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.creerCategorie)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_42 = QtWidgets.QLabel(self.creerCategorie)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_11.addWidget(self.label_42)
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_30 = QtWidgets.QLabel(self.creerCategorie)
        self.label_30.setObjectName("label_30")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.creerCategorie)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.label_31 = QtWidgets.QLabel(self.creerCategorie)
        self.label_31.setObjectName("label_31")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.textEdit_4 = QtWidgets.QTextEdit(self.creerCategorie)
        self.textEdit_4.setObjectName("textEdit_4")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEdit_4)
        self.verticalLayout_11.addLayout(self.formLayout_8)
        self.buttonBox_7 = QtWidgets.QDialogButtonBox(self.creerCategorie)
        self.buttonBox_7.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_7.setObjectName("buttonBox_7")
        self.verticalLayout_11.addWidget(self.buttonBox_7)
        self.tabWidget.addTab(self.creerCategorie, "")
        self.voirCategorie = QtWidgets.QWidget()
        self.voirCategorie.setObjectName("voirCategorie")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.voirCategorie)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_47 = QtWidgets.QLabel(self.voirCategorie)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_18.addWidget(self.label_47)
        self.formLayout_12 = QtWidgets.QFormLayout()
        self.formLayout_12.setObjectName("formLayout_12")
        self.label_48 = QtWidgets.QLabel(self.voirCategorie)
        self.label_48.setObjectName("label_48")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.voirCategorie)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_12)
        self.label_49 = QtWidgets.QLabel(self.voirCategorie)
        self.label_49.setObjectName("label_49")
        self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_49)
        self.textEdit_7 = QtWidgets.QTextEdit(self.voirCategorie)
        self.textEdit_7.setObjectName("textEdit_7")
        self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEdit_7)
        self.verticalLayout_18.addLayout(self.formLayout_12)
        self.buttonBox_11 = QtWidgets.QDialogButtonBox(self.voirCategorie)
        self.buttonBox_11.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox_11.setObjectName("buttonBox_11")
        self.verticalLayout_18.addWidget(self.buttonBox_11)
        self.tabWidget.addTab(self.voirCategorie, "")
        self.editerCategorie = QtWidgets.QWidget()
        self.editerCategorie.setObjectName("editerCategorie")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.editerCategorie)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_50 = QtWidgets.QLabel(self.editerCategorie)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_19.addWidget(self.label_50)
        self.formLayout_13 = QtWidgets.QFormLayout()
        self.formLayout_13.setObjectName("formLayout_13")
        self.label_51 = QtWidgets.QLabel(self.editerCategorie)
        self.label_51.setObjectName("label_51")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_51)
        self.label_52 = QtWidgets.QLabel(self.editerCategorie)
        self.label_52.setObjectName("label_52")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_52)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.editerCategorie)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_13)
        self.textEdit_8 = QtWidgets.QTextEdit(self.editerCategorie)
        self.textEdit_8.setObjectName("textEdit_8")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEdit_8)
        self.verticalLayout_19.addLayout(self.formLayout_13)
        self.buttonBox_12 = QtWidgets.QDialogButtonBox(self.editerCategorie)
        self.buttonBox_12.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_12.setObjectName("buttonBox_12")
        self.verticalLayout_19.addWidget(self.buttonBox_12)
        self.tabWidget.addTab(self.editerCategorie, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1098, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.boutonDepenses.setText(_translate("MainWindow", "Dépenses"))
        self.boutonCategories.setText(_translate("MainWindow", "Catégories"))
        self.boutonEntites.setText(_translate("MainWindow", "Membres"))
        self.boutonParametres.setText(_translate("MainWindow", "Paramètres"))
        self.boutonAPropos.setText(_translate("MainWindow", "À propos"))
        self.label_17.setText(_translate("MainWindow", "Logo"))
        self.label_16.setText(_translate("MainWindow", "Gestionnaire des dépenses"))
        self.label_18.setText(_translate("MainWindow", "Version:"))
        self.label_19.setText(_translate("MainWindow", "1.0"))
        self.label_20.setText(_translate("MainWindow", "Développé par:"))
        self.label_21.setText(_translate("MainWindow", "Cégep Drummondville"))
        self.label_22.setText(_translate("MainWindow", "Documentation"))
        self.label_23.setText(_translate("MainWindow", "www.lien.com"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ongletAPropos), _translate("MainWindow", "À propos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ongletParametres), _translate("MainWindow", "Paramètres"))
        self.label_36.setText(_translate("MainWindow", "Index des dépenses"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ongletDepenses), _translate("MainWindow", "Dépenses"))
        self.label_26.setText(_translate("MainWindow", "Création d\'une dépense"))
        self.label.setText(_translate("MainWindow", "Nom:"))
        self.label_2.setText(_translate("MainWindow", "Catégorie:"))
        self.label_3.setText(_translate("MainWindow", "Description:"))
        self.label_4.setText(_translate("MainWindow", "Montant:"))
        self.label_14.setText(_translate("MainWindow", "Distribution:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.creerDepense), _translate("MainWindow", "Créer"))
        self.label_25.setText(_translate("MainWindow", "Visualisation d\'une dépense"))
        self.label_5.setText(_translate("MainWindow", "Nom:"))
        self.label_6.setText(_translate("MainWindow", "Catégorie:"))
        self.label_7.setText(_translate("MainWindow", "Description:"))
        self.label_8.setText(_translate("MainWindow", "Montant:"))
        self.label_9.setText(_translate("MainWindow", "Distribution:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.voirDepense), _translate("MainWindow", "Voir"))
        self.label_24.setText(_translate("MainWindow", "Édition d\'une dépense"))
        self.label_10.setText(_translate("MainWindow", "Nom:"))
        self.label_11.setText(_translate("MainWindow", "Catégorie:"))
        self.label_12.setText(_translate("MainWindow", "Description:"))
        self.label_13.setText(_translate("MainWindow", "Montant:"))
        self.label_15.setText(_translate("MainWindow", "Distribution:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.editerDepense), _translate("MainWindow", "Éditer"))
        self.label_37.setText(_translate("MainWindow", "Index des membres"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ongletMembres), _translate("MainWindow", "Membres"))
        self.label_38.setText(_translate("MainWindow", "Création d\'un membre"))
        self.label_27.setText(_translate("MainWindow", "Nom:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.creerMembre), _translate("MainWindow", "Créer"))
        self.label_45.setText(_translate("MainWindow", "Visualisation d\'un membre"))
        self.label_46.setText(_translate("MainWindow", "Nom:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.voirMembre), _translate("MainWindow", "Voir"))
        self.label_40.setText(_translate("MainWindow", "Édition d\'un membre"))
        self.label_29.setText(_translate("MainWindow", "Nom:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.editerMembre), _translate("MainWindow", "Éditer"))
        self.label_41.setText(_translate("MainWindow", "Index des catégories"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ongletCategories), _translate("MainWindow", "Catégories"))
        self.label_42.setText(_translate("MainWindow", "Création d\'une catégorie"))
        self.label_30.setText(_translate("MainWindow", "Nom:"))
        self.label_31.setText(_translate("MainWindow", "Description:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.creerCategorie), _translate("MainWindow", "Créer"))
        self.label_47.setText(_translate("MainWindow", "Visualisation d\'une catégorie"))
        self.label_48.setText(_translate("MainWindow", "Nom:"))
        self.label_49.setText(_translate("MainWindow", "Description:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.voirCategorie), _translate("MainWindow", "Voir"))
        self.label_50.setText(_translate("MainWindow", "Édition d\'une catégorie"))
        self.label_51.setText(_translate("MainWindow", "Nom:"))
        self.label_52.setText(_translate("MainWindow", "Description:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.editerCategorie), _translate("MainWindow", "Éditer"))

