# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1098, 450)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.voletNavigation = QtWidgets.QWidget(self.centralwidget)
        self.voletNavigation.setObjectName("voletNavigation")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.voletNavigation)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.boutonDepenses = QtWidgets.QPushButton(self.voletNavigation)
        self.boutonDepenses.setCheckable(True)
        self.boutonDepenses.setAutoExclusive(True)
        self.boutonDepenses.setObjectName("boutonDepenses")
        self.verticalLayout_2.addWidget(self.boutonDepenses)
        self.boutonCategories = QtWidgets.QPushButton(self.voletNavigation)
        self.boutonCategories.setCheckable(True)
        self.boutonCategories.setAutoExclusive(True)
        self.boutonCategories.setObjectName("boutonCategories")
        self.verticalLayout_2.addWidget(self.boutonCategories)
        self.boutonMembres = QtWidgets.QPushButton(self.voletNavigation)
        self.boutonMembres.setCheckable(True)
        self.boutonMembres.setAutoExclusive(True)
        self.boutonMembres.setObjectName("boutonMembres")
        self.verticalLayout_2.addWidget(self.boutonMembres)
        self.boutonAttribution = QtWidgets.QPushButton(self.voletNavigation)
        self.boutonAttribution.setObjectName("boutonAttribution")
        self.verticalLayout_2.addWidget(self.boutonAttribution)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.boutonParametres = QtWidgets.QPushButton(self.voletNavigation)
        self.boutonParametres.setObjectName("boutonParametres")
        self.verticalLayout_2.addWidget(self.boutonParametres)
        self.boutonAPropos = QtWidgets.QPushButton(self.voletNavigation)
        self.boutonAPropos.setObjectName("boutonAPropos")
        self.verticalLayout_2.addWidget(self.boutonAPropos)
        self.horizontalLayout.addWidget(self.voletNavigation)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.onglets = QtWidgets.QTabWidget(self.centralwidget)
        self.onglets.setTabPosition(QtWidgets.QTabWidget.North)
        self.onglets.setObjectName("onglets")
        self.ongletAPropos = QtWidgets.QWidget()
        self.ongletAPropos.setObjectName("ongletAPropos")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.ongletAPropos)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_17 = QtWidgets.QLabel(self.ongletAPropos)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_7.addWidget(self.label_17)
        self.label_16 = QtWidgets.QLabel(self.ongletAPropos)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_7.addWidget(self.label_16)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_18 = QtWidgets.QLabel(self.ongletAPropos)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.ongletAPropos)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_19)
        self.label_20 = QtWidgets.QLabel(self.ongletAPropos)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.ongletAPropos)
        self.label_21.setObjectName("label_21")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_21)
        self.label_22 = QtWidgets.QLabel(self.ongletAPropos)
        self.label_22.setObjectName("label_22")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.label_23 = QtWidgets.QLabel(self.ongletAPropos)
        self.label_23.setObjectName("label_23")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_23)
        self.verticalLayout_7.addLayout(self.formLayout_4)
        self.onglets.addTab(self.ongletAPropos, "")
        self.ongletParametres = QtWidgets.QWidget()
        self.ongletParametres.setObjectName("ongletParametres")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.ongletParametres)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.onglets.addTab(self.ongletParametres, "")
        self.ongletAttribution = QtWidgets.QWidget()
        self.ongletAttribution.setObjectName("ongletAttribution")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.ongletAttribution)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_39 = QtWidgets.QLabel(self.ongletAttribution)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_9.addWidget(self.label_39)
        self.tabAttribution = QtWidgets.QTableView(self.ongletAttribution)
        self.tabAttribution.setObjectName("tabAttribution")
        self.verticalLayout_9.addWidget(self.tabAttribution)
        self.onglets.addTab(self.ongletAttribution, "")
        self.ongletPaiement = QtWidgets.QWidget()
        self.ongletPaiement.setObjectName("ongletPaiement")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.ongletPaiement)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_43 = QtWidgets.QLabel(self.ongletPaiement)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_12.addWidget(self.label_43)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_28 = QtWidgets.QLabel(self.ongletPaiement)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.label_32 = QtWidgets.QLabel(self.ongletPaiement)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.label_33 = QtWidgets.QLabel(self.ongletPaiement)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.paieChampMembre = QtWidgets.QLineEdit(self.ongletPaiement)
        self.paieChampMembre.setObjectName("paieChampMembre")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.paieChampMembre)
        self.paieChampCategorie = QtWidgets.QLineEdit(self.ongletPaiement)
        self.paieChampCategorie.setObjectName("paieChampCategorie")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.paieChampCategorie)
        self.paieChampDepense = QtWidgets.QLineEdit(self.ongletPaiement)
        self.paieChampDepense.setObjectName("paieChampDepense")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.paieChampDepense)
        self.paieChampPourcentage = QtWidgets.QLineEdit(self.ongletPaiement)
        self.paieChampPourcentage.setObjectName("paieChampPourcentage")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.paieChampPourcentage)
        self.paieChampMontant = QtWidgets.QLineEdit(self.ongletPaiement)
        self.paieChampMontant.setObjectName("paieChampMontant")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.paieChampMontant)
        self.label_34 = QtWidgets.QLabel(self.ongletPaiement)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.label_35 = QtWidgets.QLabel(self.ongletPaiement)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.verticalLayout_12.addLayout(self.formLayout_6)
        self.paieBoutonsControle = QtWidgets.QDialogButtonBox(self.ongletPaiement)
        self.paieBoutonsControle.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.paieBoutonsControle.setObjectName("paieBoutonsControle")
        self.verticalLayout_12.addWidget(self.paieBoutonsControle)
        self.onglets.addTab(self.ongletPaiement, "")
        self.ongletDepenses = QtWidgets.QWidget()
        self.ongletDepenses.setObjectName("ongletDepenses")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ongletDepenses)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_36 = QtWidgets.QLabel(self.ongletDepenses)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_4.addWidget(self.label_36)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.boutonAjouterDepense = QtWidgets.QPushButton(self.ongletDepenses)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/list-add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boutonAjouterDepense.setIcon(icon)
        self.boutonAjouterDepense.setObjectName("boutonAjouterDepense")
        self.horizontalLayout_2.addWidget(self.boutonAjouterDepense)
        self.boutonEditerDepense = QtWidgets.QPushButton(self.ongletDepenses)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/document-edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boutonEditerDepense.setIcon(icon1)
        self.boutonEditerDepense.setObjectName("boutonEditerDepense")
        self.horizontalLayout_2.addWidget(self.boutonEditerDepense)
        self.boutonVoirDepense = QtWidgets.QPushButton(self.ongletDepenses)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/visibility.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boutonVoirDepense.setIcon(icon2)
        self.boutonVoirDepense.setObjectName("boutonVoirDepense")
        self.horizontalLayout_2.addWidget(self.boutonVoirDepense)
        self.boutonRetirerDepense = QtWidgets.QPushButton(self.ongletDepenses)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/list-remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boutonRetirerDepense.setIcon(icon3)
        self.boutonRetirerDepense.setObjectName("boutonRetirerDepense")
        self.horizontalLayout_2.addWidget(self.boutonRetirerDepense)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.widget = QtWidgets.QWidget(self.ongletDepenses)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabDep = QtWidgets.QTableWidget(self.widget)
        self.tabDep.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged)
        self.tabDep.setObjectName("tabDep")
        self.tabDep.setColumnCount(0)
        self.tabDep.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tabDep)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.listDep = QtWidgets.QListWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listDep.sizePolicy().hasHeightForWidth())
        self.listDep.setSizePolicy(sizePolicy)
        self.listDep.setObjectName("listDep")
        self.horizontalLayout_3.addWidget(self.listDep)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.widget)
        self.onglets.addTab(self.ongletDepenses, "")
        self.ajouterDepense = QtWidgets.QWidget()
        self.ajouterDepense.setObjectName("ajouterDepense")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ajouterDepense)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_26 = QtWidgets.QLabel(self.ajouterDepense)
        self.label_26.setObjectName("label_26")
        self.verticalLayout.addWidget(self.label_26)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.ajouterDepense)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.creerDepenseChampNom = QtWidgets.QLineEdit(self.ajouterDepense)
        self.creerDepenseChampNom.setObjectName("creerDepenseChampNom")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.creerDepenseChampNom)
        self.label_2 = QtWidgets.QLabel(self.ajouterDepense)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.creerDepenseComboBoxCat = QtWidgets.QComboBox(self.ajouterDepense)
        self.creerDepenseComboBoxCat.setObjectName("creerDepenseComboBoxCat")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.creerDepenseComboBoxCat)
        self.label_3 = QtWidgets.QLabel(self.ajouterDepense)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.creerDepenseChampDesc = QtWidgets.QTextEdit(self.ajouterDepense)
        self.creerDepenseChampDesc.setObjectName("creerDepenseChampDesc")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.creerDepenseChampDesc)
        self.label_4 = QtWidgets.QLabel(self.ajouterDepense)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.creerDepenseSpinBoxMontant = QtWidgets.QDoubleSpinBox(self.ajouterDepense)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.creerDepenseSpinBoxMontant.sizePolicy().hasHeightForWidth())
        self.creerDepenseSpinBoxMontant.setSizePolicy(sizePolicy)
        self.creerDepenseSpinBoxMontant.setMaximumSize(QtCore.QSize(100, 16777215))
        self.creerDepenseSpinBoxMontant.setFocusPolicy(QtCore.Qt.NoFocus)
        self.creerDepenseSpinBoxMontant.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.creerDepenseSpinBoxMontant.setReadOnly(False)
        self.creerDepenseSpinBoxMontant.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.creerDepenseSpinBoxMontant.setMaximum(9999999999.0)
        self.creerDepenseSpinBoxMontant.setObjectName("creerDepenseSpinBoxMontant")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.creerDepenseSpinBoxMontant)
        self.verticalLayout.addLayout(self.formLayout)
        self.label_14 = QtWidgets.QLabel(self.ajouterDepense)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.creerDepenseTableauDistribution = QtWidgets.QTableView(self.ajouterDepense)
        self.creerDepenseTableauDistribution.setObjectName("creerDepenseTableauDistribution")
        self.verticalLayout.addWidget(self.creerDepenseTableauDistribution)
        self.creerDepenseBoutonsControle = QtWidgets.QDialogButtonBox(self.ajouterDepense)
        self.creerDepenseBoutonsControle.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.creerDepenseBoutonsControle.setObjectName("creerDepenseBoutonsControle")
        self.verticalLayout.addWidget(self.creerDepenseBoutonsControle)
        self.onglets.addTab(self.ajouterDepense, "")
        self.voirDepense = QtWidgets.QWidget()
        self.voirDepense.setObjectName("voirDepense")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.voirDepense)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_25 = QtWidgets.QLabel(self.voirDepense)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_5.addWidget(self.label_25)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.voirDepense)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.voirDepenseChampNom = QtWidgets.QLineEdit(self.voirDepense)
        self.voirDepenseChampNom.setReadOnly(True)
        self.voirDepenseChampNom.setObjectName("voirDepenseChampNom")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.voirDepenseChampNom)
        self.label_6 = QtWidgets.QLabel(self.voirDepense)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.voirDepenseChampCat = QtWidgets.QLineEdit(self.voirDepense)
        self.voirDepenseChampCat.setReadOnly(True)
        self.voirDepenseChampCat.setObjectName("voirDepenseChampCat")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.voirDepenseChampCat)
        self.label_7 = QtWidgets.QLabel(self.voirDepense)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.voirDepenseChampDesc = QtWidgets.QTextEdit(self.voirDepense)
        self.voirDepenseChampDesc.setReadOnly(True)
        self.voirDepenseChampDesc.setObjectName("voirDepenseChampDesc")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.voirDepenseChampDesc)
        self.label_8 = QtWidgets.QLabel(self.voirDepense)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.voirDepenseSpinBoxMontant = QtWidgets.QDoubleSpinBox(self.voirDepense)
        self.voirDepenseSpinBoxMontant.setMaximumSize(QtCore.QSize(100, 16777215))
        self.voirDepenseSpinBoxMontant.setFocusPolicy(QtCore.Qt.NoFocus)
        self.voirDepenseSpinBoxMontant.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.voirDepenseSpinBoxMontant.setReadOnly(True)
        self.voirDepenseSpinBoxMontant.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.voirDepenseSpinBoxMontant.setMaximum(999999999999999.0)
        self.voirDepenseSpinBoxMontant.setObjectName("voirDepenseSpinBoxMontant")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.voirDepenseSpinBoxMontant)
        self.verticalLayout_5.addLayout(self.formLayout_2)
        self.label_9 = QtWidgets.QLabel(self.voirDepense)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.voirDepenseTabDis = QtWidgets.QTableView(self.voirDepense)
        self.voirDepenseTabDis.setObjectName("voirDepenseTabDis")
        self.verticalLayout_5.addWidget(self.voirDepenseTabDis)
        self.voirDepenseBoutonsControle = QtWidgets.QDialogButtonBox(self.voirDepense)
        self.voirDepenseBoutonsControle.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.voirDepenseBoutonsControle.setObjectName("voirDepenseBoutonsControle")
        self.verticalLayout_5.addWidget(self.voirDepenseBoutonsControle)
        self.onglets.addTab(self.voirDepense, "")
        self.editerDepense = QtWidgets.QWidget()
        self.editerDepense.setObjectName("editerDepense")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.editerDepense)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_24 = QtWidgets.QLabel(self.editerDepense)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_6.addWidget(self.label_24)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtWidgets.QLabel(self.editerDepense)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.editerDepense)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.editerDepense)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.editerDepenseChampNom = QtWidgets.QLineEdit(self.editerDepense)
        self.editerDepenseChampNom.setObjectName("editerDepenseChampNom")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editerDepenseChampNom)
        self.editerDepenseChampDesc = QtWidgets.QTextEdit(self.editerDepense)
        self.editerDepenseChampDesc.setObjectName("editerDepenseChampDesc")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.editerDepenseChampDesc)
        self.label_13 = QtWidgets.QLabel(self.editerDepense)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.editerDepenseSpinBoxMontant = QtWidgets.QDoubleSpinBox(self.editerDepense)
        self.editerDepenseSpinBoxMontant.setMaximumSize(QtCore.QSize(100, 16777215))
        self.editerDepenseSpinBoxMontant.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.editerDepenseSpinBoxMontant.setReadOnly(False)
        self.editerDepenseSpinBoxMontant.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.editerDepenseSpinBoxMontant.setMaximum(999999999999.0)
        self.editerDepenseSpinBoxMontant.setObjectName("editerDepenseSpinBoxMontant")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.editerDepenseSpinBoxMontant)
        self.editerDepenseComboBoxCat = QtWidgets.QComboBox(self.editerDepense)
        self.editerDepenseComboBoxCat.setObjectName("editerDepenseComboBoxCat")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editerDepenseComboBoxCat)
        self.verticalLayout_6.addLayout(self.formLayout_3)
        self.label_15 = QtWidgets.QLabel(self.editerDepense)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.editerDepenseTabDis = QtWidgets.QTableView(self.editerDepense)
        self.editerDepenseTabDis.setObjectName("editerDepenseTabDis")
        self.verticalLayout_6.addWidget(self.editerDepenseTabDis)
        self.editerDepenseBoutonsControle = QtWidgets.QDialogButtonBox(self.editerDepense)
        self.editerDepenseBoutonsControle.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.editerDepenseBoutonsControle.setObjectName("editerDepenseBoutonsControle")
        self.verticalLayout_6.addWidget(self.editerDepenseBoutonsControle)
        self.onglets.addTab(self.editerDepense, "")
        self.ongletMembres = QtWidgets.QWidget()
        self.ongletMembres.setObjectName("ongletMembres")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.ongletMembres)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_37 = QtWidgets.QLabel(self.ongletMembres)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_14.addWidget(self.label_37)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.boutonAjouterMembre = QtWidgets.QPushButton(self.ongletMembres)
        self.boutonAjouterMembre.setIcon(icon)
        self.boutonAjouterMembre.setObjectName("boutonAjouterMembre")
        self.horizontalLayout_4.addWidget(self.boutonAjouterMembre)
        self.boutonEditerMembre = QtWidgets.QPushButton(self.ongletMembres)
        self.boutonEditerMembre.setIcon(icon1)
        self.boutonEditerMembre.setObjectName("boutonEditerMembre")
        self.horizontalLayout_4.addWidget(self.boutonEditerMembre)
        self.boutonVoirMembre = QtWidgets.QPushButton(self.ongletMembres)
        self.boutonVoirMembre.setIcon(icon2)
        self.boutonVoirMembre.setObjectName("boutonVoirMembre")
        self.horizontalLayout_4.addWidget(self.boutonVoirMembre)
        self.boutonRetirerMembre = QtWidgets.QPushButton(self.ongletMembres)
        self.boutonRetirerMembre.setIcon(icon3)
        self.boutonRetirerMembre.setObjectName("boutonRetirerMembre")
        self.horizontalLayout_4.addWidget(self.boutonRetirerMembre)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_14.addLayout(self.horizontalLayout_4)
        self.tabMem = QtWidgets.QListView(self.ongletMembres)
        self.tabMem.setObjectName("tabMem")
        self.verticalLayout_14.addWidget(self.tabMem)
        self.onglets.addTab(self.ongletMembres, "")
        self.ajouterMembre = QtWidgets.QWidget()
        self.ajouterMembre.setObjectName("ajouterMembre")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.ajouterMembre)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_38 = QtWidgets.QLabel(self.ajouterMembre)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_8.addWidget(self.label_38)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_27 = QtWidgets.QLabel(self.ajouterMembre)
        self.label_27.setObjectName("label_27")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.creerMemChampNom = QtWidgets.QLineEdit(self.ajouterMembre)
        self.creerMemChampNom.setObjectName("creerMemChampNom")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.creerMemChampNom)
        self.verticalLayout_8.addLayout(self.formLayout_5)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem5)
        self.creerMemBoutonsControle = QtWidgets.QDialogButtonBox(self.ajouterMembre)
        self.creerMemBoutonsControle.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.creerMemBoutonsControle.setObjectName("creerMemBoutonsControle")
        self.verticalLayout_8.addWidget(self.creerMemBoutonsControle)
        self.onglets.addTab(self.ajouterMembre, "")
        self.voirMembre = QtWidgets.QWidget()
        self.voirMembre.setObjectName("voirMembre")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.voirMembre)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_45 = QtWidgets.QLabel(self.voirMembre)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_17.addWidget(self.label_45)
        self.formLayout_11 = QtWidgets.QFormLayout()
        self.formLayout_11.setObjectName("formLayout_11")
        self.label_46 = QtWidgets.QLabel(self.voirMembre)
        self.label_46.setObjectName("label_46")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.voirMemChampNom = QtWidgets.QLineEdit(self.voirMembre)
        self.voirMemChampNom.setObjectName("voirMemChampNom")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.voirMemChampNom)
        self.verticalLayout_17.addLayout(self.formLayout_11)
        self.label_53 = QtWidgets.QLabel(self.voirMembre)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_17.addWidget(self.label_53)
        self.voirMemTabDep = QtWidgets.QTableView(self.voirMembre)
        self.voirMemTabDep.setObjectName("voirMemTabDep")
        self.verticalLayout_17.addWidget(self.voirMemTabDep)
        self.voirMemBoutonsControle = QtWidgets.QDialogButtonBox(self.voirMembre)
        self.voirMemBoutonsControle.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.voirMemBoutonsControle.setObjectName("voirMemBoutonsControle")
        self.verticalLayout_17.addWidget(self.voirMemBoutonsControle)
        self.onglets.addTab(self.voirMembre, "")
        self.editerMembre = QtWidgets.QWidget()
        self.editerMembre.setObjectName("editerMembre")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.editerMembre)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_40 = QtWidgets.QLabel(self.editerMembre)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_10.addWidget(self.label_40)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem6)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_29 = QtWidgets.QLabel(self.editerMembre)
        self.label_29.setObjectName("label_29")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.editerMemChampNom = QtWidgets.QLineEdit(self.editerMembre)
        self.editerMemChampNom.setObjectName("editerMemChampNom")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editerMemChampNom)
        self.verticalLayout_10.addLayout(self.formLayout_7)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem7)
        self.editerMemBoutonsControle = QtWidgets.QDialogButtonBox(self.editerMembre)
        self.editerMemBoutonsControle.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.editerMemBoutonsControle.setObjectName("editerMemBoutonsControle")
        self.verticalLayout_10.addWidget(self.editerMemBoutonsControle)
        self.onglets.addTab(self.editerMembre, "")
        self.ongletCategories = QtWidgets.QWidget()
        self.ongletCategories.setObjectName("ongletCategories")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.ongletCategories)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_41 = QtWidgets.QLabel(self.ongletCategories)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_15.addWidget(self.label_41)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.boutonAjouterCategorie = QtWidgets.QPushButton(self.ongletCategories)
        self.boutonAjouterCategorie.setIcon(icon)
        self.boutonAjouterCategorie.setObjectName("boutonAjouterCategorie")
        self.horizontalLayout_5.addWidget(self.boutonAjouterCategorie)
        self.boutonEditerCategorie = QtWidgets.QPushButton(self.ongletCategories)
        self.boutonEditerCategorie.setIcon(icon1)
        self.boutonEditerCategorie.setObjectName("boutonEditerCategorie")
        self.horizontalLayout_5.addWidget(self.boutonEditerCategorie)
        self.boutonVoirCategorie = QtWidgets.QPushButton(self.ongletCategories)
        self.boutonVoirCategorie.setIcon(icon2)
        self.boutonVoirCategorie.setObjectName("boutonVoirCategorie")
        self.horizontalLayout_5.addWidget(self.boutonVoirCategorie)
        self.boutonRetirerCategorie = QtWidgets.QPushButton(self.ongletCategories)
        self.boutonRetirerCategorie.setIcon(icon3)
        self.boutonRetirerCategorie.setObjectName("boutonRetirerCategorie")
        self.horizontalLayout_5.addWidget(self.boutonRetirerCategorie)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout_15.addLayout(self.horizontalLayout_5)
        self.tabCat = QtWidgets.QTableView(self.ongletCategories)
        self.tabCat.setObjectName("tabCat")
        self.verticalLayout_15.addWidget(self.tabCat)
        self.onglets.addTab(self.ongletCategories, "")
        self.ajouterCategorie = QtWidgets.QWidget()
        self.ajouterCategorie.setObjectName("ajouterCategorie")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.ajouterCategorie)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_42 = QtWidgets.QLabel(self.ajouterCategorie)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_11.addWidget(self.label_42)
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_30 = QtWidgets.QLabel(self.ajouterCategorie)
        self.label_30.setObjectName("label_30")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.creerCatChampNom = QtWidgets.QLineEdit(self.ajouterCategorie)
        self.creerCatChampNom.setObjectName("creerCatChampNom")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.creerCatChampNom)
        self.label_31 = QtWidgets.QLabel(self.ajouterCategorie)
        self.label_31.setObjectName("label_31")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.creerCatChampDesc = QtWidgets.QTextEdit(self.ajouterCategorie)
        self.creerCatChampDesc.setObjectName("creerCatChampDesc")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.creerCatChampDesc)
        self.verticalLayout_11.addLayout(self.formLayout_8)
        self.creerCatBoutonsControle = QtWidgets.QDialogButtonBox(self.ajouterCategorie)
        self.creerCatBoutonsControle.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.creerCatBoutonsControle.setObjectName("creerCatBoutonsControle")
        self.verticalLayout_11.addWidget(self.creerCatBoutonsControle)
        self.onglets.addTab(self.ajouterCategorie, "")
        self.voirCategorie = QtWidgets.QWidget()
        self.voirCategorie.setObjectName("voirCategorie")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.voirCategorie)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_47 = QtWidgets.QLabel(self.voirCategorie)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_18.addWidget(self.label_47)
        self.formLayout_12 = QtWidgets.QFormLayout()
        self.formLayout_12.setObjectName("formLayout_12")
        self.label_48 = QtWidgets.QLabel(self.voirCategorie)
        self.label_48.setObjectName("label_48")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.voirCatChampNom = QtWidgets.QLineEdit(self.voirCategorie)
        self.voirCatChampNom.setObjectName("voirCatChampNom")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.voirCatChampNom)
        self.label_49 = QtWidgets.QLabel(self.voirCategorie)
        self.label_49.setObjectName("label_49")
        self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_49)
        self.voirCatChampDesc = QtWidgets.QTextEdit(self.voirCategorie)
        self.voirCatChampDesc.setObjectName("voirCatChampDesc")
        self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.voirCatChampDesc)
        self.verticalLayout_18.addLayout(self.formLayout_12)
        self.label_54 = QtWidgets.QLabel(self.voirCategorie)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_18.addWidget(self.label_54)
        self.voirCatTabDep = QtWidgets.QTableView(self.voirCategorie)
        self.voirCatTabDep.setObjectName("voirCatTabDep")
        self.verticalLayout_18.addWidget(self.voirCatTabDep)
        self.voirCatBoutonsControle = QtWidgets.QDialogButtonBox(self.voirCategorie)
        self.voirCatBoutonsControle.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.voirCatBoutonsControle.setObjectName("voirCatBoutonsControle")
        self.verticalLayout_18.addWidget(self.voirCatBoutonsControle)
        self.onglets.addTab(self.voirCategorie, "")
        self.editerCategorie = QtWidgets.QWidget()
        self.editerCategorie.setObjectName("editerCategorie")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.editerCategorie)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_50 = QtWidgets.QLabel(self.editerCategorie)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_19.addWidget(self.label_50)
        self.formLayout_13 = QtWidgets.QFormLayout()
        self.formLayout_13.setObjectName("formLayout_13")
        self.label_51 = QtWidgets.QLabel(self.editerCategorie)
        self.label_51.setObjectName("label_51")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_51)
        self.label_52 = QtWidgets.QLabel(self.editerCategorie)
        self.label_52.setObjectName("label_52")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_52)
        self.editerCatChampNom = QtWidgets.QLineEdit(self.editerCategorie)
        self.editerCatChampNom.setObjectName("editerCatChampNom")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editerCatChampNom)
        self.editerCatChampDesc = QtWidgets.QTextEdit(self.editerCategorie)
        self.editerCatChampDesc.setObjectName("editerCatChampDesc")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editerCatChampDesc)
        self.verticalLayout_19.addLayout(self.formLayout_13)
        self.editerCatBoutonsControle = QtWidgets.QDialogButtonBox(self.editerCategorie)
        self.editerCatBoutonsControle.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.editerCatBoutonsControle.setObjectName("editerCatBoutonsControle")
        self.verticalLayout_19.addWidget(self.editerCatBoutonsControle)
        self.onglets.addTab(self.editerCategorie, "")
        self.horizontalLayout.addWidget(self.onglets)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.onglets.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.boutonDepenses.setText(_translate("MainWindow", "Dépenses"))
        self.boutonCategories.setText(_translate("MainWindow", "Catégories"))
        self.boutonMembres.setText(_translate("MainWindow", "Membres"))
        self.boutonAttribution.setText(_translate("MainWindow", "Attribution"))
        self.boutonParametres.setText(_translate("MainWindow", "Paramètres"))
        self.boutonAPropos.setText(_translate("MainWindow", "À propos"))
        self.label_17.setText(_translate("MainWindow", "Logo"))
        self.label_16.setText(_translate("MainWindow", "Gestionnaire des dépenses"))
        self.label_18.setText(_translate("MainWindow", "Version:"))
        self.label_19.setText(_translate("MainWindow", "1.0"))
        self.label_20.setText(_translate("MainWindow", "Développé par:"))
        self.label_21.setText(_translate("MainWindow", "Cégep Drummondville"))
        self.label_22.setText(_translate("MainWindow", "Documentation"))
        self.label_23.setText(_translate("MainWindow", "www.lien.com"))
        self.onglets.setTabText(self.onglets.indexOf(self.ongletAPropos), _translate("MainWindow", "À propos"))
        self.onglets.setTabText(self.onglets.indexOf(self.ongletParametres), _translate("MainWindow", "Paramètres"))
        self.label_39.setText(_translate("MainWindow", "Attribution:"))
        self.onglets.setTabText(self.onglets.indexOf(self.ongletAttribution), _translate("MainWindow", "Attribution"))
        self.label_43.setText(_translate("MainWindow", "Paiement:"))
        self.label_28.setText(_translate("MainWindow", "Membre:"))
        self.label_32.setText(_translate("MainWindow", "Catégorie:"))
        self.label_33.setText(_translate("MainWindow", "Dépense:"))
        self.label_34.setText(_translate("MainWindow", "Montant:"))
        self.label_35.setText(_translate("MainWindow", "%:"))
        self.onglets.setTabText(self.onglets.indexOf(self.ongletPaiement), _translate("MainWindow", "Paiement"))
        self.label_36.setText(_translate("MainWindow", "Index des dépenses"))
        self.boutonAjouterDepense.setText(_translate("MainWindow", "Créer"))
        self.boutonEditerDepense.setText(_translate("MainWindow", "Éditer"))
        self.boutonVoirDepense.setText(_translate("MainWindow", "Voir"))
        self.boutonRetirerDepense.setText(_translate("MainWindow", "Retirer"))
        self.onglets.setTabText(self.onglets.indexOf(self.ongletDepenses), _translate("MainWindow", "Dépenses"))
        self.label_26.setText(_translate("MainWindow", "Création d\'une dépense"))
        self.label.setText(_translate("MainWindow", "Nom:"))
        self.label_2.setText(_translate("MainWindow", "Catégorie:"))
        self.label_3.setText(_translate("MainWindow", "Description:"))
        self.label_4.setText(_translate("MainWindow", "Montant:"))
        self.label_14.setText(_translate("MainWindow", "Distribution:"))
        self.onglets.setTabText(self.onglets.indexOf(self.ajouterDepense), _translate("MainWindow", "Créer"))
        self.label_25.setText(_translate("MainWindow", "Visualisation d\'une dépense"))
        self.label_5.setText(_translate("MainWindow", "Nom:"))
        self.label_6.setText(_translate("MainWindow", "Catégorie:"))
        self.label_7.setText(_translate("MainWindow", "Description:"))
        self.label_8.setText(_translate("MainWindow", "Montant:"))
        self.label_9.setText(_translate("MainWindow", "Distribution:"))
        self.onglets.setTabText(self.onglets.indexOf(self.voirDepense), _translate("MainWindow", "Voir"))
        self.label_24.setText(_translate("MainWindow", "Édition d\'une dépense"))
        self.label_10.setText(_translate("MainWindow", "Nom:"))
        self.label_11.setText(_translate("MainWindow", "Catégorie:"))
        self.label_12.setText(_translate("MainWindow", "Description:"))
        self.label_13.setText(_translate("MainWindow", "Montant:"))
        self.label_15.setText(_translate("MainWindow", "Distribution:"))
        self.onglets.setTabText(self.onglets.indexOf(self.editerDepense), _translate("MainWindow", "Éditer"))
        self.label_37.setText(_translate("MainWindow", "Index des membres"))
        self.boutonAjouterMembre.setText(_translate("MainWindow", "Créer"))
        self.boutonEditerMembre.setText(_translate("MainWindow", "Éditer"))
        self.boutonVoirMembre.setText(_translate("MainWindow", "Voir"))
        self.boutonRetirerMembre.setText(_translate("MainWindow", "Retirer"))
        self.onglets.setTabText(self.onglets.indexOf(self.ongletMembres), _translate("MainWindow", "Membres"))
        self.label_38.setText(_translate("MainWindow", "Création d\'un membre"))
        self.label_27.setText(_translate("MainWindow", "Nom:"))
        self.onglets.setTabText(self.onglets.indexOf(self.ajouterMembre), _translate("MainWindow", "Créer"))
        self.label_45.setText(_translate("MainWindow", "Visualisation d\'un membre"))
        self.label_46.setText(_translate("MainWindow", "Nom:"))
        self.label_53.setText(_translate("MainWindow", "Dépenses:"))
        self.onglets.setTabText(self.onglets.indexOf(self.voirMembre), _translate("MainWindow", "Voir"))
        self.label_40.setText(_translate("MainWindow", "Édition d\'un membre"))
        self.label_29.setText(_translate("MainWindow", "Nom:"))
        self.onglets.setTabText(self.onglets.indexOf(self.editerMembre), _translate("MainWindow", "Éditer"))
        self.label_41.setText(_translate("MainWindow", "Index des catégories"))
        self.boutonAjouterCategorie.setText(_translate("MainWindow", "Créer"))
        self.boutonEditerCategorie.setText(_translate("MainWindow", "Éditer"))
        self.boutonVoirCategorie.setText(_translate("MainWindow", "Voir"))
        self.boutonRetirerCategorie.setText(_translate("MainWindow", "Retirer"))
        self.onglets.setTabText(self.onglets.indexOf(self.ongletCategories), _translate("MainWindow", "Catégories"))
        self.label_42.setText(_translate("MainWindow", "Création d\'une catégorie"))
        self.label_30.setText(_translate("MainWindow", "Nom:"))
        self.label_31.setText(_translate("MainWindow", "Description:"))
        self.onglets.setTabText(self.onglets.indexOf(self.ajouterCategorie), _translate("MainWindow", "Créer"))
        self.label_47.setText(_translate("MainWindow", "Visualisation d\'une catégorie"))
        self.label_48.setText(_translate("MainWindow", "Nom:"))
        self.label_49.setText(_translate("MainWindow", "Description:"))
        self.label_54.setText(_translate("MainWindow", "Dépenses:"))
        self.onglets.setTabText(self.onglets.indexOf(self.voirCategorie), _translate("MainWindow", "Voir"))
        self.label_50.setText(_translate("MainWindow", "Édition d\'une catégorie"))
        self.label_51.setText(_translate("MainWindow", "Nom:"))
        self.label_52.setText(_translate("MainWindow", "Description:"))
        self.onglets.setTabText(self.onglets.indexOf(self.editerCategorie), _translate("MainWindow", "Éditer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

